### Background

The dataset in question was generated from a series of experiments conducted by Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz in 2012.  THe experiments used a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING\_UPSTAIRS, WALKING\_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. 
Using its embedded accelerometer and gyroscope, the experimenters captured 3-axial linear acceleration and 3-axial angular velocity signals at a constant rate of 50Hz. The experiments were video-recorded to label the data manually. The obtained dataset was randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force was assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

The features selected for this database came from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

* tBodyAcc-XYZ
* tGravityAcc-XYZ
* tBodyAccJerk-XYZ
* tBodyGyro-XYZ
* tBodyGyroJerk-XYZ
* tBodyAccMag
* tGravityAccMag
* tBodyAccJerkMag
* tBodyGyroMag
* tBodyGyroJerkMag
* fBodyAcc-XYZ
* fBodyAccJerk-XYZ
* fBodyGyro-XYZ
* fBodyAccMag
* fBodyAccJerkMag
* fBodyGyroMag
* fBodyGyroJerkMag

The set of variables that were estimated from these signals were: 

* mean(): Mean value
* std(): Standard deviation
* mad(): Median absolute deviation 
* max(): Largest value in array
* min(): Smallest value in array
* sma(): Signal magnitude area
* energy(): Energy measure. Sum of the squares divided by the number of values
* iqr(): Interquartile range
* entropy(): Signal entropy
* arCoeff(): Autorregresion coefficients with Burg order equal to 4
* correlation(): correlation coefficient between two signals
* maxInds(): index of the frequency component with largest magnitude
* meanFreq(): Weighted average of the frequency components to obtain a mean frequency
* skewness(): skewness of the frequency domain signal
* kurtosis(): kurtosis of the frequency domain signal
* bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window
* angle(): Angle between to vectors

Additional vectors were obtained by averaging the signals in a signal window sample. These were used on the angle() variable:

* gravityMean
* tBodyAccMean
* tBodyAccJerkMean
* tBodyGyroMean
* tBodyGyroJerkMean

### The Problem

A subset of data confined only to variables that referenced mean and standard deviation measurements for the combinations of activities and observations was required, with further summarization of data that summarized these measures by subject by activity.  This required recombining the various datasets listed above.  An assumption was made that the order of observations matched the order of subjects which also matched the order of activities.

### The Data

The dataset was split into several subsidiary files:

* x_test.txt: contained the raw measurements and computed summaries for each observation, split from master data at 70%
* x_training.txt: contained the raw measurements and computed summaries for each observation, split from master data 30%
* subject_train.txt: contained the IDs for each subject observation assigned to TRAIN group
* subject_test.txt: contained the IDs for each subject observation assigned to TEST group
* y_train.txt: contained the coded activity values for each observation assigned to TRAIN group
* y_test.txt: contained the coded activity values for each observation assigned to TEST group
* activity\_labels.txt: contained coded (1-6) values for activities (WALKING, WALKING\_UPSTAIRS, WALKING\_DOWNSTAIRS, SITTING, STANDING, LAYING) monitored in the experiment
* features.txt: contained 561 variable names representing the both the measurements (in volts) and measurement summaries (also in volts)


### Data Manipulation and Analysis Plan

*An assumption is made that the user has downloaded and unzipped into a directory named .../Desktop/Coursera the data files required for this project.*

1. Read each dataset into an R data frame
2. Clarify column names
3. Combine the data frames created in step 1
4. Extract subsets of subjects, activities and measurements for any variable identified as a mean or standard deviation summary
5. Combine the subsets of subjects, activities and measurements into a master subset
6. Install and make available the plyr package
7. Create a summary by subject by activity type of the data frame created in step 5
8. Create a text file version of the data frame created iin step 7 frame with the variables listed below:
 
### Output Variables

*Note that, with exception of the Subject ID and Activity Type variables, all other measurements are in (V)olts.*

| **Column Number** | **Variable Name and Description** |
  
| 1 | *Subject ID:* Unique identifier assigned to participants in the experiment |

| 2 | *Activity Type:* Activity codes recoded from original to more clearly describe the experimental activities as follows:
    1. Walking
    2. Walking Upstairs
    3. Walking Downstairs
    4. Sitting
    5. Standing
    6. Laying
    |
    

| 3 |  *Body\_Linear\_Acceleration\_Mean\_X\_Axis:* Computed Average of Body Linear Acceleration measurement means for the designated activity on X axis via accelerometer sensor data 
 
|

| 4 | *Body\_Linear\_Acceleration\_Mean\_Y\_Axis:* Computed Average of Body Linear Acceleration measurement means for the designated activity on Y axis from accelerometer sensor data 

|

| 5 | *Body\_Linear\_Acceleration\_Mean\_Z\_Axis:* Computed Average of Body Linear Acceleration measurement means for the designated activity on Z axis from accelerometer sensor data     |

| 6 | *Gravity\_Linear\_Acceleration\_Mean\_X\_Axis:* Computed Average of Body Linear Acceleration measurement means for the designated activity on X axis from gravity sensor data   |

| 7 | *Gravity\_Linear\_Acceleration\_Mean\_Y\_Axis:* Computed Average of Body Linear Acceleration measurement means for the designated activity on Y axis from gravity sensor data     |

| 8 | *Gravity\_Linear\_Acceleration\_Mean\_Z\_Axis:* Computed Average of Body Linear Acceleration measurement means for the designated activity on Z axis from gravity sensor data     |

| 9 | *Body\_Linear\_Acceleration\_Over\_Time\_Mean\_X\_Axis:* Computed Average of Body Linear Acceleration over Time (Jerk) means for the designated activity on X axis from accelerometer sensor data     |

| 10 | *Body\_Linear\_Acceleration\_Over\_Time\_Mean\_Y\_Axis:* Computed Average of Body Linear Acceleration over Time (Jerk) means for the designated activity on Y axis from accelerometer sensor data    |

| 11 | *Body\_Linear\_Acceleration\_Over\_Time\_Mean\_Z\_Axis:* Computed Average of Body Linear Acceleration over Time (Jerk) means for the designated activity on Z axis from accelerometer sensor data    |

| 12 | *Body\_Angular\_Velocity\_Mean\_X\_Axis:* Computed Average of Body Angular Velocity measurement means for the designated activity on X axis via gyroscope sensor data  Units of Measurement: Volts   |

| 13 | *Body\_Angular\_Velocity\_Mean\_Y\_Axis: *Computed Average of Body Angular Velocity measurement means for the designated activity on Y axis via gyroscope sensor data     |

| 14 | *Body\_Angular\_Velocity\_Mean\_Z\_Axis* Computed Average of Body Angular Velocity measurement means for the designated activity on Z axis via gyroscope sensor data     |

| 15 | *Body\_Angular\_Velocity\_Over\_Time\_Mean\_X\_Axis:* Computed Average of Body Angular Velocity over Time (Jerk) means for the designated activity on X axis from accelerometer sensor data     |

| 16 | *Body\_Angular\_Velocity\_Over\_Time\_Mean\_Y\_Axis:* Computed Average of Body Angular Velocity over Time (Jerk) means for the designated activity on Y axis from accelerometer sensor data     |

| 17 | *Body\_Angular\_Velocity\_Over\_Time\_Mean\_Z\_Axis:* Computed Average of Body Angular Velocity over Time (Jerk) means for the designated activity on Z axis from accelerometer sensor data     |

| 18 | *Body\_Linear\_Acceleration\_Magnitude\_Mean:* Average mean for magnitude of Linear Acceleration derived from accelerometer sensor data (gravity readings)    |

| 19 | *Gravity\_Linear\_Acceleration\_Magnitude\_Mean:* Average mean for magnitude of Linear Acceleration derived from accelerometer sensor data (gravity readings)     |

| 20 | *Body\_Linear\_Acceleration\_Over\_Time\_Magnitude\_Mean:* Average mean for magnitude of Linear Acceleration over time (Jerk) derived from accelerometer sensor data      |

| 21 | *Body\_Angular\_Velocity\_Magnitude\_Mean:* Average mean for magnitude of Body Angular Velocity over time (Jerk) derived from gyroscope sensor data   Units of Measurement: Volts   |

| 22 | *Body\_Angular\_Velocity\_Over\_Time\_Magnitude\_Mean:* Average mean for magnitude of Body Angular Velocity over time (Jerk) derived from gyroscope sensor data      |

| 23 | *FFT\_Body\_Linear\_Acceleration\_Mean\_X\_Axis:* Computed Average of FFT (Fast Fourier Transform) applied to Body Linear Acceleration measurement means for the designated activity on X axis via accelerometer sensor data     |

| 24 | *FFT\_Body\_Linear\_Acceleration\_Mean\_Y\_Axis:*  Computed Average of FFT (Fast Fourier Transform) applied to Body Linear Acceleration measurement means for the designated activity on Y axis via accelerometer sensor data     |

| 25 | *FFT\_Body\_Linear\_Acceleration\_Mean\_Z\_Axis:* Computed Average of FFT (Fast Fourier Transform) applied to Body Linear Acceleration measurement means for the designated activity on Z axis via accelerometer sensor data    |

| 26 | *FFT\_Body\_Linear\_Acceleration\_Mean\_FreqX\_Axis:* Computed average of FFT (Fast Fourier Transform) applied to mean frequency of Body Linear Measurement means on X axis     |

| 27 | *FFT\_Body\_Linear\_Acceleration\_Mean\_FreqY\_Axis:* Computed average of FFT (Fast Fourier Transform) applied to mean frequency of Body Linear Measurement means on Y axis     |

| 28 | *FFT\_Body\_Linear\_Acceleration\_Mean\_FreqZ\_Axis:* Computed average of FFT (Fast Fourier Transform) applied to mean frequency of Body Linear Measurement means on Z axis     |

| 29 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Mean\_X\_Axis:* Computed Average of FFT (Fast Fourier Transform) Body Linear Acceleration over Time (Jerk) means for the designated activity on X axis from accelerometer sensor data     |

| 30 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Mean\_Y\_Axis:* Computed Average of FFT (Fast Fourier Transform) Body Linear Acceleration over Time (Jerk) means for the designated activity on Y axis from accelerometer sensor data     |

| 31 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Mean\_Z\_Axis:* Computed Average of FFT (Fast Fourier Transform) Body Linear Acceleration over Time (Jerk) means for the designated activity on Z axis from accelerometer sensor data     |

| 32 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Mean\_FreqX\_Axis:* Computed average of FFT (Fast Fourier Transform) applied to mean frequency of Body Linear Measurement over time (Jerk) means on X axis    |

| 33 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Mean\_FreqY\_Axis:* Computed average of FFT (Fast Fourier Transform) applied to mean frequency of Body Linear Measurement over time (Jerk) means on Y axis     |

| 34 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Mean\_FreqZ\_Axis:* Computed average of FFT (Fast Fourier Transform) applied to mean frequency of Body Linear Measurement over time (Jerk) means on Z axis    |

| 35 | *FFT\_Body\_Angular\_Velocity\_Mean\_X\_Axis* Computed Average of FFT (Fast Fourier Transform) Body Angular Velocity measurement means for the designated activity on X axis via gyroscope sensor data     |

| 36 | *FFT\_Body\_Angular\_Velocity\_Mean\_Y\_Axis* Computed Average of FFT (Fast Fourier Transform) Body Angular Velocity measurement means for the designated activity on Y axis via gyroscope sensor data     |

| 37 | *FFT\_Body\_Angular\_Velocity\_Mean\_Z\_Axis* Computed Average of FFT (Fast Fourier Transform) Body Angular Velocity measurement means for the designated activity on Z axis via gyroscope sensor data     |

| 38 | *FFT\_Body\_Angular\_Velocity\_Mean\_FreqX\_Axis:* Computed average of FFT (Fast Fourier Transform) applied to mean frequency of Body Angular Velocity means on X axis    |

| 39 | *FFT\_Body\_Angular\_Velocity\_Mean\_FreqY\_Axis:* Computed average of FFT (Fast Fourier Transform) applied to mean frequency of Body Angular Velocity means on Y axis     |

| 40 | *FFT\_Body\_Angular\_Velocity\_Mean\_FreqZ\_Axis:* Computed average of FFT (Fast Fourier Transform) applied to mean frequency of Body Angular Velocity means on Z axis     |

| 41 | *FFT\_Body\_Linear\_Acceleration\_Magnitude\_Mean:* Computed average of FFT (Fast Fourier Transform) applied to average mean for magnitude of Linear Acceleration derived from accelerometer sensor data (gravity readings)     |

| 42 | *FFT\_Body\_Linear\_Acceleration\_Magnitude\_Mean\_Freq:* Computed average of FFT( Fast Fourier Transform) applied to average mean for magnitude of Linear Acceleration derived from accelerometer sensor data (gravity readings)     |

| 43 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Magnitude\_Mean:* Computed average of FFT (Fast Fourier Transform) applied to average mean for magnitude of Linear Acceleration over time (Jerk) derived from accelerometer sensor data     |

| 44 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Magnitude\_Mean\_Freq:* Computed average of FFT (Fast Fourier Transform) appled to average mean frequency of Linear Acceleration over time (Jerk) derived from accelerometer sensor data    |

| 45 | *FFT\_Body Angular Velocity\_Magnitude\_Mean:* Computed average of FFT (Fast Fourier Transform) applied to average mean for angular velocity derived from gyroscope sensor data     |

| 46 | *FFT\_Body Angular\_Velocity\_Magnitude\_Mean\_Freq:* Computed average of FFT (Fast Fourier Transform) applied to average mean frequency for magnitude of Angular Velocity derived from gyroscope sensor data     |

| 47 | *FFT\_Body Angular\_Velocity\_Over\_Time\_Magnitude\_Mean:* Computed average of FFT (Fast Fourier Transform) applied to average mean for magnitude of Angular Velocity derived from gyroscope sensor data     |

| 48 | *FFT\_Body\_Angular\_Velocity\_Over\_Time\_Magnitude\_Mean\_Freq:* Computed average of FFT (Fast Fourier Transform) applied to average mean frequency for magnitude of Angular Velocity derived from gyroscope sensor data      |

| 49 | *Body\_Linear\_Acceleration\_Std\_Dev\_X\_AxisS:* Standard Deviation of Linear Acceleration signals on X axis for each designated activity from accelerometer sensor    |

| 50 | *Body\_Linear\_Acceleration\_Std\_Dev\_Y\_Axis:* Standard Deviation of Linear Acceleration signals on Y axis for each designated activity from accelerometer sensor    |

| 51 | *Body\_Linear\_Acceleration\_Std\_Dev\_Z\_Axis:* Standard Deviation of Linear Acceleration signals on Z axis for each designated activity from accelerometer sensor     |

| 52 | *Gravity\_Linear\_Acceleration\_Std\_Dev\_X\_Axis:* Standard Deviation of Gravity Linear Acceleration signals on X axis for each designated activity from accelerometer sensor     |

| 53 | *Gravity\_Linear\_Acceleration\_Std\_Dev\_Y\_Axis:* Standard Deviation of Gravity Linear Acceleration signals on Y axis for each designated activity from accelerometer sensor     |

| 54 | *Gravity\_Linear\_Acceleration\_Std\_Dev\_Z\_Axis:* Standard Deviation of Gravity Linear Acceleration signals on Z axis for each designated activity from accelerometer sensor     |

| 55 | *Body\_Linear\_Acceleration\_Over\_Time\_Std\_Dev\_X\_Axis:* Standard Deviation of Linear Acceleration signals over time (Jerk) on X axis for each designated activity from accelerometer sensor     |

| 56 | *Body\_Linear\_Acceleration\_Over\_Time\_Std\_Dev\_Y\_Axis:* Standard Deviation of Linear Acceleration signals over time (Jerk) on Y axis for each designated activity from accelerometer sensor     |

| 57 | *Body\_Linear\_Acceleration\_Over\_Time\_Std\_Dev\_Z\_Axis:* Standard Deviation of Linear Acceleration signals over time (Jerk) on Z axis for each designated activity from accelerometer sensor   |

| 58 | *Body\_Angular\_Velocity\_Std\_Dev\_X\_Axis:* Standard Deviation of Angular Velocity signals on X axis for each designated activity from gyroscope sensor     |

| 59 | *Body\_Angular\_Velocity\_Std\_Dev\_Y\_Axis:* Standard Deviation of Angular Velocity signals on Y axis for each designated activity from gyroscope sensor    |

| 60 | *Body\_Angular\_Velocity\_Std\_Dev\_Z\_Axis:* Standard Deviation of Angular Velocity signals on Z axis for each designated activity from gyroscope sensor     |

| 61 | *Body\_Angular\_Velocity\_Over\_Time\_Std\_Dev\_X\_Axis:* Standard Deviation of Angular Velocity signals over time (Jerk) on X axis for each designated activity from gyroscope sensor     |

| 62 | *Body\_Angular\_Velocity\_Over\_Time\_Std\_Dev\_Y\_Axis:* Standard Deviation of Angular Velocity signals over time (Jerk) on Y axis for each designated activity from gyroscope sensor     |

| 63 | *Body\_Angular\_Velocity\_Over\_Time\_Std\_Dev\_Z\_Axis:* Standard Deviation of Angular Velocity signals over time (Jerk) on Z axis for each designated activity from gyroscope sensor     |

| 64 | *Body\_Linear\_Acceleration\_Magnitude\_Std\_Dev:* Standard Deviation of magnitude of Linear Acceleration derived from accelerometer sensor data     |

| 65 | *Gravity\_Linear\_Acceleration\_Magnitude\_Std\_Dev:* Standard Deviation of magnitude of Linear Acceleration derived from accelerometer sensor data (gravity)     |

| 66 | *Body\_Linear\_Acceleration\_Over\_Time\_Magnitude\_Std\_Dev:* Standard Deviation of magnitude of Linear Acceleration over time (Jerk) derived from accelerometer sensor data      |

| 67 | *Body\_Angular\_Velocity\_Magnitude\_Std\_Dev:* Standard Deviation of magnitude of Body Angular Velocity derived from gyroscope sensor data   Units of Measurement: Volts   |

| 68 | *Body\_Angular\_Velocity\_Over\_Time\_Magnitude\_Std\_Dev:* Standard Deviation of magnitude of Body Angular Velocity over time (Jerk) derived from gyroscope sensor data      |

| 69 | *FFT\_Body\_Linear\_Acceleration\_Std\_Dev\_X\_Axis:* FFT (Fast Fourier Transform) applied to computed Standard Deviation of Body Linear Acceleration measurement means for the designated activity on X axis via accelerometer sensor data      |

| 70 | *FFT\_Body\_Linear\_Acceleration\_Std\_Dev\_Y\_Axis* FFT (Fast Fourier Transform) applied to computed Standard Deviation of Body Linear Acceleration measurement means for the designated activity on Y axis via accelerometer sensor data      |

| 71 | *FFT\_Body\_Linear\_Acceleration\_Std\_Dev\_Z\_Axis:* FFT (Fast Fourier Transform) applied to computed Standard Deviation of Body Linear Acceleration measurement means for the designated activity on Z axis via accelerometer sensor data      |

| 72 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Std\_Dev\_X\_Axis:* FFT (Fast Fourier Transform) applied to computed Standard Deviation of Body Linear Acceleration over Time (Jerk) means for the designated activity on X axis from accelerometer sensor data    |

| 73 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Std\_Dev\_Y\_Axis:* FFT (Fast Fourier Transform) applied to computed Standard Deviation of Body Linear Acceleration over Time (Jerk) means for the designated activity on Y axis from accelerometer sensor data     |

| 74 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Std\_Dev\_Z\_Axis:* FFT (Fast Fourier Transform) applied to computed Standard Deviation of Body Linear Acceleration over Time (Jerk) means for the designated activity on Z axis from accelerometer sensor data    |

| 75 | *FFT\_Body\_Angular\_Velocity\_Std\_Dev\_X\_Axis:* FFT (Fast Fourier Transform) applied to computed Standard Deviation Body Angular Velocity measurement means for the designated activity on X axis via gyroscope sensor data     |

| 76 | *FFT\_Body\_Angular\_Velocity\_Std\_Dev\_Y\_Axis:* FFT (Fast Fourier Transform) applied to computed Standard Deviation Body Angular Velocity measurement means for the designated activity on Y axis via gyroscope sensor data     |

| 77 | *FFT\_Body\_Angular\_Velocity\_Std\_Dev\_Z\_Axis:* FFT (Fast Fourier Transform) applied to computed Standard Deviation Body Angular Velocity measurement means for the designated activity on Z axis via gyroscope sensor data   |

| 78 | *FFT\_Body\_Linear\_Acceleration\_Magnitude\_Std\_Dev:* FFT (Fast Fourier Transform) applied to Standard Deviation magnitude of Linear Acceleration derived from accelerometer sensor data     |

| 79 | *FFT\_Body\_Linear\_Acceleration\_Over\_Time\_Magnitude\_Std\_Dev:* FFT (Fast Fourier Transform) applied to Standard Deviation magnitude of Linear Acceleration over time (Jerk) derived from accelerometer sensor data      |

| 80 | *FFT\_Body\_Angular\_Velocity\_Magnitude\_Std\_Dev:* FFT (Fast Fourier Transform) applied to Standard Deviation magnitude of Angular Velocity derived from gyroscope sensor data      |

| 81 | *FFT\_Body\_Angular Velocity\_Over\_Time\_Magnitude\_Std\_Dev:* FFT (Fast Fourier Transform) applied to Standard Deviation magnitude of Angular Velocity over time (Jerk) derived from gyroscope sensor data      |





      
      
